
DROP TABLE Products CASCADE;
DROP TABLE Monitors CASCADE;
DROP TABLE Cpus CASCADE;
DROP TABLE Gpus CASCADE;
DROP TABLE Monoblocks CASCADE;
DROP TABLE Users CASCADE;
DROP TABLE Reviews CASCADE;
DROP TABLE ReviewRevs CASCADE;

DROP TYPE IF EXISTS UINT;
DROP TYPE IF EXISTS CpuVendor;
DROP TYPE IF EXISTS GpuVendor;
